version: '3.8'

services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: smaraa-postgres
    environment:
      POSTGRES_DB: smaraa_bot
      POSTGRES_USER: smaraa_user
      POSTGRES_PASSWORD: smaraa_password
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U smaraa_user -d smaraa_bot']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
